meta:
  app_id: verndale_hackathon_opal_cms12
  display_name: Verndale Hackathon Opal Cms12
  version: 1.0.0-dev.1
  vendor: verndale
  summary: An example of an Opal Tool that connects to CMS 12 and assists with page creation.
  support_url: https://www.verndale.com
  contact_email: doug.yoder@verndale.com
  categories:
    - Productivity
  availability:
    - us

runtime: node22

functions:
  opal_tool:
    entry_point: OpalToolFunction
    description: Opal tool function
  language_branches_tool:
    entry_point: LanguageBranchesFunction
    description: Tools for listing and retrieving Optimizely CMS language branches