meta:
  app_id: verndale_hackathon_cms12_test
  display_name: Verndale Hackathon Opal Cms12 - TEST
  version: 1.0.0-dev.5
  vendor: verndale
  summary: An example of an Opal Tool that connects to CMS 12 and assists with page creation.
  support_url: https://www.verndale.com
  contact_email: doug.yoder@verndale.com
  categories:
    - Productivity
  availability:
    - us

runtime: node22

functions:
  opal_tool:
    entry_point: OpalToolFunction
    description: Opal tool function
  content_definitions:
    entry_point: OptiCMSContentDefinitionsAPITool
    description: Optimizely CMS Content Definitions API tool
  content_definitions_content_types:
    entry_point: OptiCMSContentDefinitionsContentTypesAPITool
    description: Optimizely CMS Content Definitions API - Content Types
  content_management:
    entry_point: OptiCMSContentManagementAPITool
    description: Optimizely CMS Content Management API tool
