sections:
  - key: instructions
    label: Instructions
    elements:
      - type: instructions
        text: Paste the URL(s) below into `Discovery URL` field in Opal account `Tools` section.
      - type: text
        key: opal_content_definitions_tool_url
        label: Opal Tool URL for CMS Content Definitions
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Definitions tool.
      - type: text
        key: opal_content_management_tool_url
        label: Opal Tool URL for CMS Content Management API
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Management API tool.

  - key: auth
    label: Authentication
    elements:
      - type: instructions
        text: CMS Connection Information

      - type: text
        key: cms_base_url
        label: CMS Base URL
        disabled: false
        required: true
        help: The base URL of your CMS instance (e.g., https://your-cms-instance.com)
        hint: https://your-cms-instance.com

      # (kept) Original API-key style fields, no longer required so they don't block Basic Auth
      - type: text
        key: basic_username
        label: Basic Auth Username (optional)
        disabled: false
        required: false
        help: Username for Basic Auth when using on-prem or dev environments
      - type: secret
        key: basic_password
        label: Basic Auth Password (optional)
        disabled: false
        required: false
        help: Password for Basic Auth. If provided, overrides Bearer token.
      - type: button
        label: Authorize
        style: primary
        action: authorize
