sections:
  - key: instructions
    label: Instructions
    elements:
      - type: instructions
        text: Paste the URL(s) below into `Discovery URL` field in Opal account `Tools` section.
      - type: text
        key: opal_content_definitions_tool_url
        label: Opal Tool URL for CMS Content Definitions
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Definitions tool.
      - type: text
        key: opal_content_management_tool_url
        label: Opal Tool URL for CMS Content Management API
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Management API tool.
      - type: divider
      - type: instructions
        text: Paste the URL above into `Discovery URL` field in Opal account `Tools` section.
  # uncomment if you want to use bearer token authentication
  #  - key: bearer_token
  #    label: Bearer Token
  #    elements:
  #      - type: secret
  #        key: bearer_token
  #        label: Bearer Token (optional)
  #        help: |
  #          If you want to use bearer token for authentication, paste it here. You will have to configure it in Opal registry settings.
  #          Otherwise, leave it empty.
  #      - type: button
  #        label: Save token
  #        action: save_token

  #=====================================================================================================================
  # Sample OAuth section
  #=====================================================================================================================
  #- key: oauth
  #  label: OAuth authorization
  #  properties:
  #    - authorized
  #  elements:
  #    - type: instructions
  #      text: Please continue to Google to authorize the connection with ODP
  #    - type: oauth_button
  #      label: Authorize with Google
  #    - type: instructions
  #      text: |
  #        ** ⚠️ You need to perform the authorization to start to sync data. ⚠️ **
  #      visible:
  #        key: oauth.authorized
  #        equals: false
  - key: cms_api
    label: Optimizely CMS API
    elements:
      - type: text
        key: base_url
        required: true
        label: CMS Base URL
        help: |
          Base URL for your Optimizely CMS APIs, e.g. https://cms.mycompany.com
        hint: https://cms.example.com
      - type: button
        action: save_cms_api
        label: Save CMS API
