sections:
  - key: instructions
    label: Instructions
    elements:
      - type: instructions
        text: Paste the URL(s) below into `Discovery URL` field in Opal account `Tools` section.
      - type: text
        key: opal_content_definitions_tool_url
        label: Opal Tool URL for CMS Content Definitions
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Definitions tool.
      - type: text
        key: opal_content_management_tool_url
        label: Opal Tool URL for CMS Content Management API
        disabled: true
        help: Paste the URL below into your Opal tool settings to enable the CMS Content Management API tool.

  - key: auth
    label: Authentication
    elements:
      - type: instructions
        text: CMS Connection Information

      - type: text
        key: cms_base_url
        label: CMS Base URL
        disabled: false
        required: true
        help: The base URL of your CMS instance (e.g., https://your-cms-instance.com)
        hint: https://your-cms-instance.com

      - type: text
        key: basic_username
        label: Basic Auth Username (optional)
        disabled: false
        required: false
        help: Username for Basic Auth when using on-prem or dev environments
      - type: secret
        key: basic_password
        label: Basic Auth Password (optional)
        disabled: false
        required: false
        help: Password for Basic Auth. If provided, overrides Bearer token.

      - type: text
        key: cms_cd_client_id
        label: CMS Content Definitions API Client ID
        disabled: false
        required: true
        help: The Client ID used for the Content Definitions API
        hint: your-client-id
      - type: secret
        key: cms_cd_api_key
        label: CMS Content Definitions API Key
        disabled: false
        required: true
        help: The API Key for the Content Definitions API

      - type: text
        key: cms_cm_client_id
        label: CMS Content Management API Client ID
        disabled: false
        required: true
        help: The CMS username for the Content Management API
      - type: secret
        key: cms_cm_api_key
        label: CMS Content Management API Password
        disabled: false
        required: true
        help: The CMS password


      - type: button
        label: Authorize
        style: primary
        action: authorize
